# Generated by Django 2.2 on 2019-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email_verified',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='mobile_verified',
            field=models.BooleanField(blank=True),
        ),
    ]
