# Generated by Django 2.2 on 2019-04-30 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dds2app', '0003_auto_20190429_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sender',
            name='mobile_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=80, unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dds2app_attachment_created_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dds2app_attachment_modified_related', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dds2app.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
